name: awesome-react-query

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7-buster

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install awesome_bot
        run: gem install awesome_bot

      - name: Run awesome_bot
        run: awesome_bot README.md
