name: awesome-react-query

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7-buster

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install awesome_bot
      run: gem install awesome_bot
    
    # Run awesome_bot on README
    - name: Run awesome_bot
      run: awesome_bot README.md

    - name: awesome-lint versionless
      uses: jthegedus/github-action-awesome-lint@v0.1.0
